<?php

namespace AppBundle\Repository;

/**
 * Historique_employerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Historique_employerRepository extends \Doctrine\ORM\EntityRepository
{
}
