<?php

namespace AppBundle\Repository;

/**
 * RevenuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RevenuesRepository extends \Doctrine\ORM\EntityRepository
{
}
