<?php

namespace AppBundle\Repository;

/**
 * SpendTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpendTimeRepository extends \Doctrine\ORM\EntityRepository
{
}
