<?php

namespace AppBundle\Repository;

/**
 * TempsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempsRepository extends \Doctrine\ORM\EntityRepository
{
}
